### ISSUE TITLE
Typed-Protocols Redesign (Tech Debt)

### ISSUE THREAD

**Issue by coot** [IntersectMBO/cardano-node#4169]
# Objective

Finish (review) the redesign of typed-protocols.  The goal was two fold:
* provide a simpler more functional API
* reduce number of threads needed to run pipelined mini-protocols

## Development plan

* [ ] input-output-hk/cardano-node#4221 (top level issue)

Pull requests:
* [ ] input-output-hk/typed-protocols#3 (in review)
* [ ] input-output-hk/ouroboros-network#3675
* [ ] input-output-hk/ekg-forward#5
* [ ] input-output-hk/cardano-node#3845

# Impact

The following applications will be affected:

* `db-sync`
* `cardano-wallet`

# Risks

This is a major change of one of the key components of the networking stack.  It also required major changes in the block-fetch application.  It is now considered that this piece of work should be released on it's own in a new `cardano-node` release.

# Dependencies

none

# Reverse Dependencies

* input-output-hk/ouroboros-network#3941
* ~input-output-hk/ouroboros-network#3886~
* genesis

**Comment by coot** [comment]
Closing. Instead IntersectMBO/ouroboros-network#4936 will be done.
