### ISSUE TITLE
1.35.3 SCOPE 

### ISSUE THREAD

**Issue by CarlosLopezDeLara** [IntersectMBO/cardano-node#4257]
# 1.35.3

### Plutus
- [x] Condition SECP256k1 to the protocol version 8  ([#4795](https://github.com/input-output-hk/plutus/pull/4795))

### Ledger
- [x] MinFee bug bix ([#2938](https://github.com/input-output-hk/cardano-ledger/pull/2938))
- https://github.com/input-output-hk/cardano-node/pull/4242
### Node
- [x] Protocol in header to announce 7.2 ([#4260](https://github.com/input-output-hk/cardano-node/pull/4260))
- [x] Fix `leadership-schedule` ([#4106](https://github.com/input-output-hk/cardano-node/pull/4106))
- [x] `build` and `build-raw` commands to accept simple reference minting scripts ([#4087](https://github.com/input-output-hk/cardano-node/pull/4087))
- [x] Add utxoCostPerByte protocol parameter ([#4141](https://github.com/input-output-hk/cardano-node/pull/4141))
- [x] Building Alonzo transactions from Babbage era ([#4135](https://github.com/input-output-hk/cardano-node/pull/4135))
- [x] Fix `Kes-period-info` ([#3945](https://github.com/input-output-hk/cardano-node/pull/3945))
- [x] Fix `protocol-state`  ([#4102](https://github.com/input-output-hk/cardano-node/pull/4102))
- [x] `build` to allow all invalid scripts ([#4088](https://github.com/input-output-hk/cardano-node/pull/4088))
- [x] Render reference script hashes when using `--calculate-plutus-script-cost`([#4204](https://github.com/input-output-hk/cardano-node/pull/4204))
- [x] Fix building of Alonzo transaction in Babbage ([#4166](https://github.com/input-output-hk/cardano-node/pull/4166))

**Comment by jfruiz11375** [comment]
I have updated to 1.35.3-testnet-only and now see the below error. My 1.35.2 node is still running with no issues on testnet.

[cardanon:cardano.node.ErrorPolicy:Notice:465] [2022-08-03 22:39:15.89 UTC] IP 3.72.26.163:3001 ErrorPolicySuspendConsumer (Just (ConnectionExceptionTrace (SubscriberError {seType = SubscriberParallelConnectionCancelled, seMessage = "Parallel connection cancelled", seStack = []}))) 1s
[cardanon:cardano.node.ErrorPolicy:Notice:465] [2022-08-03 22:39:15.89 UTC] IP 18.198.216.177:3001 ErrorPolicySuspendConsumer (Just (ConnectionExceptionTrace (SubscriberError {seType = SubscriberParallelConnectionCancelled, seMessage = "Parallel connection cancelled", seStack = []}))) 1s
[cardanon:cardano.node.ErrorPolicy:Notice:465] [2022-08-03 22:39:15.89 UTC] IP 3.72.137.52:3001 ErrorPolicySuspendConsumer (Just (ConnectionExceptionTrace (SubscriberError {seType = SubscriberParallelConnectionCancelled, seMessage = "Parallel connection cancelled", seStack = []}))) 1s
[cardanon:cardano.node.ErrorPolicy:Notice:465] [2022-08-03 22:39:15.89 UTC] IP 3.131.32.242:3001 ErrorPolicySuspendConsumer (Just (ConnectionExceptionTrace (SubscriberError {seType = SubscriberParallelConnectionCancelled, seMessage = "Parallel connection cancelled", seStack = []}))) 1s
[cardanon:cardano.node.ErrorPolicy:Notice:465] [2022-08-03 22:39:15.89 UTC] IP 54.199.108.71:3001 ErrorPolicySuspendConsumer (Just (ConnectionExceptionTrace (SubscriberError {seType = SubscriberParallelConnectionCancelled, seMessage = "Parallel connection cancelled", seStack = []}))) 1s
[cardanon:cardano.node.ChainDB:Notice:444] [2022-08-03 22:39:16.14 UTC] Chain extended, new tip: f58545f02a8961b17256a888ea2722bcf60fd4fe25e317daa96c6391048d97f2 at slot 64387391
[cardanon:cardano.node.ChainDB:Notice:444] [2022-08-03 22:39:18.23 UTC] Chain extended, new tip: f11d161b26d73e2ef6b7d96e53cabba8a2d3305c3fa162e0ab0a6642188d5393 at slot 64387992
[cardanon:cardano.node.ChainDB:Notice:444] [2022-08-03 22:39:19.48 UTC] Chain extended, new tip: 70e41bf110741eafef0dd821af33eab28ec04d811bfc7113e499ad32437e5a1c at slot 64394492
[cardanon:cardano.node.ChainDB:Notice:444] [2022-08-03 22:39:20.76 UTC] Chain extended, new tip: 9295bc64291688bb0c9b4f0af92d7fb37f1ae670956b71cbaa44904bb61d1834 at slot 64400330
[cardanon:cardano.node.ChainDB:Error:444] [2022-08-03 22:39:20.78 UTC] Invalid block 470b412e2ab520b348f4ddd200bf3b8cf51fda49cdf449cba07a38f0d27c7a6b at slot 64400487: ExtValidationErrorLedger (HardForkLedgerErrorFromEra S (S (S (S (S (Z (WrapLedgerErr {unwrapLedgerErr = BBodyError (BlockTransitionError [ShelleyInAlonzoPredFail (LedgersFailure (LedgerFailure (UtxowFailure (MalformedScriptWitnesses (fromList [ScriptHash "f79a9c7749dccb4cba4f4e2b1d395503abf3b21afa39887c3fe60254"])))))])})))))))
[cardanon:cardano.node.ChainDB:Info:444] [2022-08-03 22:39:20.78 UTC] Valid candidate a39c50470f6615ee765d65e532a44f48f26c921932bcabd13ee4e6ac09826532 at slot 64400358

**Comment by btbf** [comment]
@jfruiz11375 

#4252 
As reported here, 1.35.3-testnetonly is deprecated for public testnet.
The current recommended version of the public testnet is 1.35.2.

**Comment by jfruiz11375** [comment]
Thanks for the info

Javier Ruiz
Independent Database Consultant
Database Administration Services

“We cannot solve our problems with the same thinking we used to create them”

My sites

http://db12c.blogspot.com/

http://cloudcontrol12c.blogspot.com/
