### ISSUE TITLE
UTXO-HD: Prepare LMDB implementation for benchmarking

### ISSUE THREAD

**Issue by jasagredo** [IntersectMBO/cardano-node#5697]
- [x] Rebase the UTXO-HD implementation on top of `cardano-node` 8.9.0 once it lands on master (#5691).
- [x] Allow to choose the ledgerdb backend via flags (currently disabled)
- [x] Finish the rework of range queries (currently disabled) Fixed in V1, tentatively fixed in V2
- [x] Complete the new tracing system traces in the UTXO-HD branch (not implemented due to taking shortcuts)
  - [x] Backing store traces in V1 makes the legacy system output too much (breaking ellision). Maybe not important?
- [x] Expose a flag `--ssd-database-dir PATH` for LMDB live tables
- [x] Expose a flag `--ssd-snapshot-state` for deciding to store the serialization of `LedgerState blk EmptyMK` in the ssd dir.
- [x] Expose a flag `--ssd-snapshot-tables` for deciding to store the copied LMDB tables in the ssd dir.
- [x] Tests passing in `ouroboros-consensus`
- [x] Tests passing in `cardano-api`
- [x] Tests passing in `cardano-node`
- [x] Redesign the access to the new epoch state for `getEpochState` in `cardano-api`
- [x] Make sure that the snapshots work as expected (`NumOfDiskSnapshots` and them being duplicated in UTXO-HD) (IntersectMBO/ouroboros-consensus#1018, IntersectMBO/ouroboros-consensus#1016)
- [ ] MIGHT WAIT FOR INITIAL TESTING: Re-enable `ouroboros-consensus` benchmarks (IntersectMBO/ouroboros-consensus#1021)

# Branches

- https://github.com/IntersectMBO/ouroboros-consensus/pull/977
- https://github.com/IntersectMBO/cardano-api/pull/494
- https://github.com/IntersectMBO/cardano-node/pull/5726

# Known issues
- [x] Consensus: Aarch64-darwin in Hydra fail when building ghc-9.6.4 https://ci.iog.io/build/3537346/nixlog/1
- [x] Cardano-api: Mingw32 compilation in cardano-api crashes: https://ci.iog.io/build/3537497/nixlog/1
- [x] Node: Legacy tracers need a review
- [x] Node: New tracers are stubs. Also because of this, tests are failing in `cardano-node-test: Configuration Consistency tests`, for example https://github.com/IntersectMBO/cardano-node/actions/runs/8570639554/job/23488999528
- [ ] Cardano-api and node: there are some HLint warnings that we should address before merging.
- [ ] Consensus mempool benchmarks showed a regression. System level benchmarks will show whether such a regression is real. Bechmarks are disabled at the moment.
- [ ] Documentation is outdated. 
   - InMemory V2 is not mentioned at all
   - `ouroboros-consensus-cardano-legacy-block` is still mentioned
